export const syntheticPeopleCatalog = [
  ["Lucía Martín", "Operaciones", "Responsable de operaciones"],
  ["Álvaro Romero", "Producto", "Responsable de producto"],
  ["Carmen Vidal", "Tecnología", "Responsable de plataforma"],
  ["Hugo Navarro", "Atención", "Responsable de experiencia"],
  ["Sofía Campos", "Datos", "Analista de datos"],
  ["Daniel Ortega", "Administración", "Especialista financiero"],
  ["Elena Costa", "Operaciones", "Coordinadora de procesos"],
  ["Marcos León", "Producto", "Diseñador de producto"],
  ["Irene Salas", "Tecnología", "Ingeniera frontend"],
  ["Pablo Ríos", "Atención", "Especialista de soporte"],
  ["Nora Ferrer", "Datos", "Analista de información"],
  ["Adrián Vega", "Administración", "Analista de control"],
  ["Claudia Serra", "Operaciones", "Gestora de proyectos"],
  ["Mateo Lozano", "Producto", "Analista funcional"],
  ["Julia Pastor", "Tecnología", "Ingeniera backend"],
  ["Leo Cabrera", "Atención", "Técnico de soporte"],
  ["Valeria Prieto", "Datos", "Ingeniera de datos"],
  ["Bruno Molina", "Administración", "Especialista laboral"],
  ["Aitana Rey", "Operaciones", "Analista de procesos"],
  ["Sergio Peña", "Producto", "Investigador de experiencia"],
  ["Marta Soler", "Tecnología", "Especialista de calidad"],
  ["Nicolás Blanco", "Atención", "Gestor de servicio"],
  ["Emma Galán", "Datos", "Analista de calidad"],
  ["Álex Fuentes", "Administración", "Técnico administrativo"],
  ["Vega Santamaría", "Operaciones", "Coordinadora de capacidad"],
  ["Rubén Pardo", "Producto", "Coordinador de producto"],
  ["Lara Moya", "Tecnología", "Especialista de sistemas"],
  ["Samuel Cano", "Atención", "Analista de incidencias"],
  ["Olivia Núñez", "Datos", "Consultora analítica"],
  ["Gonzalo Iglesias", "Administración", "Controller financiero"],
  ["Inés Pascual", "Operaciones", "Gestora de automatización"],
  ["Mario Arias", "Tecnología", "Arquitecto de soluciones"],
] as const;

export const syntheticProjectCatalog = [
  ["CLIENT", "Portal de clientes", "Unifica solicitudes, documentación y seguimiento en una experiencia autoservicio."],
  ["DATA", "Calidad del dato", "Eleva la fiabilidad de los datos operativos mediante reglas, alertas y responsables."],
  ["AUTO", "Automatización de operaciones", "Reduce tareas repetitivas con flujos auditables y recuperación ante errores."],
  ["SUPPORT", "Experiencia de soporte", "Mejora la clasificación, respuesta y resolución de solicitudes internas."],
  ["CAPACITY", "Planificación de capacidad", "Conecta demanda, disponibilidad y prioridades para anticipar cuellos de botella."],
  ["FINOPS", "Control financiero", "Consolida importaciones, conciliación y previsiones de tesorería agregada."],
  ["PEOPLE", "Experiencia de personas", "Simplifica el directorio, la disponibilidad y los cambios de equipo."],
  ["INSIGHT", "Indicadores operativos", "Define indicadores comunes y recorridos de análisis para toda la organización."],
  ["MOBILE", "Operación móvil", "Adapta los flujos prioritarios a equipos que trabajan fuera del escritorio."],
  ["RELIAB", "Fiabilidad de integraciones", "Aumenta la observabilidad y la recuperación de sincronizaciones nocturnas."],
  ["SECURE", "Gobierno de accesos", "Refuerza permisos, revisiones y trazabilidad sin exponer datos sensibles."],
  ["CONTENT", "Comunicación interna", "Moderniza la creación, revisión y publicación de novedades operativas."],
] as const;

export const syntheticTaskActions = [
  "Definir criterios de aceptación",
  "Validar el flujo con el equipo",
  "Preparar el tablero de seguimiento",
  "Revisar dependencias técnicas",
  "Documentar decisiones de diseño",
  "Configurar alertas de calidad",
  "Ajustar permisos por rol",
  "Analizar resultados de la prueba",
  "Resolver observaciones de accesibilidad",
  "Preparar la revisión funcional",
  "Optimizar la consulta agregada",
  "Verificar el comportamiento adaptable",
  "Diseñar el plan de contingencia",
  "Actualizar la guía operativa",
  "Contrastar métricas con el periodo anterior",
  "Revisar la trazabilidad de eventos",
] as const;

export const syntheticIncidentCatalog = [
  ["Importación nocturna retrasada", "La ejecución terminó fuera de la ventana prevista y requiere revisar la cola."],
  ["Permiso de edición incorrecto", "Un rol de consulta muestra una acción que debería permanecer bloqueada."],
  ["Movimientos duplicados en revisión", "La regla de idempotencia ha enviado varias filas a la bandeja de excepciones."],
  ["Sincronización parcial del directorio", "Una ejecución completó los cambios de equipo pero dejó pendientes varias altas."],
  ["Lentitud en el panel de indicadores", "La consulta agregada tarda más de lo esperado al aplicar varios filtros."],
  ["Desfase en el estado del proyecto", "El resumen de proyectos no refleja todavía la última actualización de salud."],
  ["Notificación interna no entregada", "Una asignación reciente no aparece en la bandeja de la persona responsable."],
  ["Conciliación automática incompleta", "Algunos movimientos no encuentran una regla de categoría suficientemente precisa."],
  ["Vista guardada sin filtros", "La vista recuperada conserva el nombre pero no todos los criterios seleccionados."],
  ["SLA calculado con calendario anterior", "La fecha objetivo utiliza una política previa al último cambio de configuración."],
  ["Dependencia bloqueada sin aviso", "Una tarea pasó a bloqueada sin actualizar el indicador de la iniciativa."],
  ["Publicación programada pendiente", "La novedad superó su hora de publicación y continúa en estado de revisión."],
] as const;

export const syntheticTreasuryConcepts = [
  ["Ingresos por servicios", "Operación"],
  ["Aportación a programa", "Financiación"],
  ["Cuota de colaboración", "Ingresos recurrentes"],
  ["Regularización de proyecto", "Ajustes"],
  ["Servicios de infraestructura", "Tecnología"],
  ["Licencias de software", "Tecnología"],
  ["Servicios profesionales", "Operación"],
  ["Gastos de desplazamiento", "Actividad"],
  ["Suministros de oficina", "Administración"],
  ["Costes de comunicación", "Actividad"],
] as const;

export const syntheticNewsCatalog = [
  "Nuevo resumen de la actividad",
  "Mejoras en la planificación de capacidad",
  "Tableros de trabajo más ágiles",
  "Seguimiento ampliado de integraciones",
  "Nuevos controles de calidad del dato",
  "Experiencia renovada para vacaciones",
  "Proyectos con señales de riesgo",
  "Conciliación asistida de movimientos",
  "Perfil y preferencias más personalizables",
  "Accesibilidad reforzada en toda la plataforma",
  "Indicadores agregados de nómina",
  "Novedades con una presentación editorial",
] as const;
